# site settings

title: Sai Parthiv Bandikallu's Personal Website
description: My personal website for online CV
tag-long: My personal website for online CV
tag-short: Jekyll theme
url: https://saiparthiv.me
baseurl: ""
permalink: pretty
repo: https://github.com/saiparthiv/saiparthiv.github.io
photo: /assets/mypic.JPG

# author settings

author:
  name: Sai Parthiv Bandikallu
  email: saiparthiv95@gmail.com


# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
